# Generated by Django 4.2.6 on 2023-11-11 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 10, 14, 6, 265553, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
